export { default as Gallery } from './gallery'
export { default as Details } from './details'
export { default as ColorPicker } from './colorPicker'
export { default as AddToCart } from './addToCart'
export { default as Container } from './container'
export { default as Filter } from './filter'
